steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/sturdy-filament-447809-f8/test-repository/imagedockername',
    '-f',
    'test.Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/sturdy-filament-447809-f8/test-repository/imagedockername',
  ]
#options:
#  logging: CLOUD_LOGGING_ONLY